/**
 * Encode every Speech Line's words with macOS `say` into TMS5220 frames and
 * write src/data/speech.ts. Run with `npm run speech`; needs macOS. The
 * speech ROMs are never read: the voices here are the system's.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { BREATH, PAUSE, SPEAKERS, SPEECH_LINES, type Speaker } from '../src/audio/speechLines.ts';
import { analyse, breathFrames, packFrames, readWav } from './lpc.ts';

const dir = mkdtempSync(join(tmpdir(), 'starwars-speech-'));
const words = new Map<string, Speaker>();
for (const line of Object.values(SPEECH_LINES)) {
  for (const word of line.words) if (word !== PAUSE && word !== BREATH && !words.has(word)) words.set(word, line.speaker);
}

const toHex = (bytes: Uint8Array) => Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
const entries: string[] = [];
let index = 0;
for (const [word, speaker] of words) {
  const { voice, rate, pitchScale } = SPEAKERS[speaker];
  const file = join(dir, `${index++}.wav`);
  execFileSync('say', ['-v', voice, '-r', String(rate), '-o', file, '--data-format=LEI16@8000', word.toLowerCase()]);
  const wav = readWav(readFileSync(file));
  if (wav.rate !== 8000) throw new Error(`${word}: say produced ${wav.rate} Hz`);
  const frames = analyse(wav.samples, { pitchScale });
  const voiced = frames.filter((f) => f.pitch > 0).length;
  console.log(`${speaker.padEnd(6)} ${word.padEnd(52)} ${frames.length} frames, ${voiced} voiced`);
  entries.push(`  ${JSON.stringify(word)}: { frames: ${frames.length}, data: '${toHex(packFrames(frames))}' },`);
}
const breath = breathFrames();
entries.push(`  ${JSON.stringify(BREATH)}: { frames: ${breath.length}, data: '${toHex(packFrames(breath))}' },`);

const out = `/**
 * Speech words as TMS5220 frame streams: generated by \`npm run speech\` from
 * macOS \`say\` through scripts/encodeSpeech.ts. Do not edit by hand. Each entry
 * is the frame count (25 ms each, the last a stop frame) and the packed
 * frames in hex.
 */
export const SPEECH_WORDS: Record<string, { frames: number; data: string }> = {
${entries.join('\n')}
};
`;
writeFileSync('src/data/speech.ts', out);
console.log(`wrote src/data/speech.ts with ${entries.length} words`);
